import type { KnownBlock } from '@slack/bolt';
import type { PatternMatch } from '../../contracts/events';
import type { ActionResults } from '../../contracts/services';

export const buildActionCard = (
  pattern: PatternMatch | null,
  results: ActionResults
): KnownBlock[] => {
  const header = pattern
    ? `*⚡ Flint detected friction*\n${pattern.summary}`
    : `*⚡ Flint acted on your request*\n${results.summary}`;

  const fields = results.succeeded.map((r) => ({
    type: 'mrkdwn' as const,
    text: `✅ *${r.tool.toUpperCase()}*\n<${r.url ?? '#'}|${r.description}>`
  }));

  const card: KnownBlock[] = [
    { type: 'section', text: { type: 'mrkdwn', text: header } }
  ];

  if (fields.length > 0) {
    card.push({ type: 'section', fields });
  }

  card.push({
    type: 'actions',
    elements: [
      {
        type: 'button',
        text: { type: 'plain_text', text: 'View details' },
        action_id: 'flint_view_details',
        value: pattern?.id ?? 'manual'
      },
      {
        type: 'button',
        text: { type: 'plain_text', text: 'Undo' },
        style: 'danger',
        action_id: 'flint_undo',
        value: pattern?.id ?? 'manual'
      },
      {
        type: 'button',
        text: { type: 'plain_text', text: 'Escalate' },
        action_id: 'flint_escalate',
        value: pattern?.id ?? 'manual'
      }
    ]
  });

  card.push({
    type: 'context',
    elements: [{ type: 'mrkdwn', text: '_Generated by Flint · AI-assisted, human-reviewed_' }]
  });

  return card;
};
